services:
  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp-server

    ports:
      - "21:21"
      - "30000-30009:30000-30009"

    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: admin
      FTP_USER_PASS: admin123
      FTP_USER_HOME: /home/admin

    volumes:
      - ./ftp-data:/home/admin

    restart: unless-stopped