alimentos = {
    # =========================
    # PROTEÍNAS
    # =========================
    "pollo": "Proteina",
    "pechuga de pollo": "Proteina",
    "muslo de pollo": "Proteina",
    "ala de pollo": "Proteina",
    "carne": "Proteina",
    "res": "Proteina",
    "lomo de res": "Proteina",
    "carne molida": "Proteina",
    "bistec": "Proteina",
    "filete de res": "Proteina",
    "cerdo": "Proteina",
    "lomo de cerdo": "Proteina",
    "costilla de cerdo": "Proteina",
    "chuleta de cerdo": "Proteina",
    "pavo": "Proteina",
    "jamon": "Proteina",
    "pescado": "Proteina",
    "salmon": "Proteina",
    "atun": "Proteina",
    "sardina": "Proteina",
    "trucha": "Proteina",
    "tilapia": "Proteina",
    "bacalao": "Proteina",
    "merluza": "Proteina",
    "caballa": "Proteina",
    "arenque": "Proteina",
    "anchoa": "Proteina",
    "huevo": "Proteina",
    "huevo de codorniz": "Proteina",
    "camaron": "Proteina",
    "langostino": "Proteina",
    "cangrejo": "Proteina",
    "langosta": "Proteina",
    "calamar": "Proteina",
    "pulpo": "Proteina",
    "mejillon": "Proteina",
    "ostra": "Proteina",
    "almeja": "Proteina",

    # =========================
    # FRUTAS
    # =========================
    "manzana": "Fruta",
    "pera": "Fruta",
    "banano": "Fruta",
    "platano": "Fruta",
    "naranja": "Fruta",
    "mandarina": "Fruta",
    "tangerina": "Fruta",
    "limon": "Fruta",
    "lima": "Fruta",
    "toronja": "Fruta",
    "pomelo": "Fruta",
    "fresa": "Fruta",
    "mora": "Fruta",
    "frambuesa": "Fruta",
    "arandano": "Fruta",
    "cereza": "Fruta",
    "uva": "Fruta",
    "mango": "Fruta",
    "papaya": "Fruta",
    "piña": "Fruta",
    "sandia": "Fruta",
    "melon": "Fruta",
    "kiwi": "Fruta",
    "coco": "Fruta",
    "maracuya": "Fruta",
    "granadilla": "Fruta",
    "guayaba": "Fruta",
    "guanabana": "Fruta",
    "curuba": "Fruta",
    "lulo": "Fruta",
    "uchuva": "Fruta",
    "tomate de arbol": "Fruta",
    "feijoa": "Fruta",
    "pitahaya": "Fruta",
    "zapote": "Fruta",
    "mamey": "Fruta",
    "nispero": "Fruta",
    "ciruela": "Fruta",
    "durazno": "Fruta",
    "melocoton": "Fruta",
    "nectarina": "Fruta",
    "albaricoque": "Fruta",
    "higo": "Fruta",
    "granada": "Fruta",
    "caqui": "Fruta",
    "persimmon": "Fruta",
    "carambola": "Fruta",
    "tamarindo": "Fruta",
    "datil": "Fruta",
    "maracuya amarillo": "Fruta",
    "pitaya": "Fruta",
    "acai": "Fruta",
    "rambutan": "Fruta",
    "lichi": "Fruta",
    "mangostino": "Fruta",
    "kiwano": "Fruta",

    # =========================
    # VERDURAS
    # =========================
    "zanahoria": "Verdura",
    "tomate": "Verdura",
    "lechuga": "Verdura",
    "espinaca": "Verdura",
    "brocoli": "Verdura",
    "coliflor": "Verdura",
    "pepino": "Verdura",
    "cebolla": "Verdura",
    "cebolla roja": "Verdura",
    "cebolla blanca": "Verdura",
    "ajo": "Verdura",
    "pimenton": "Verdura",
    "pimiento": "Verdura",
    "aji": "Verdura",
    "apio": "Verdura",
    "berenjena": "Verdura",
    "calabacin": "Verdura",
    "zucchini": "Verdura",
    "remolacha": "Verdura",
    "repollo": "Verdura",
    "repollo morado": "Verdura",
    "acelga": "Verdura",
    "arveja": "Verdura",
    "espinaca": "Verdura",
    "esparrago": "Verdura",
    "alcachofa": "Verdura",
    "col rizada": "Verdura",
    "kale": "Verdura",
    "coles de bruselas": "Verdura",
    "berros": "Verdura",
    "rucula": "Verdura",
    "radicheta": "Verdura",
    "nabo": "Verdura",
    "rabano": "Verdura",
    "puerro": "Verdura",
    "champiñon": "Verdura",
    "hongos": "Verdura",
    "maiz tierno": "Verdura",
    "habichuela": "Verdura",
    "judia verde": "Verdura",
    "vainita": "Verdura",
    "calabaza": "Verdura",
    "auyama": "Verdura",
    "zapallo": "Verdura",
    "chayote": "Verdura",
    "quinua verde": "Verdura",
    "palmito": "Verdura",
    "yuca": "Verdura",
    "papa": "Verdura",
    "batata": "Verdura",
    "camote": "Verdura",
    "ñame": "Verdura",
    "jengibre": "Verdura",
    "cilantro": "Verdura",
    "perejil": "Verdura",
    "albahaca": "Verdura",
    "menta": "Verdura",
    "romero": "Verdura",
    "tomillo": "Verdura"
}